-- =============================================================================
-- Relatório de METAS por RCA (vendedor) — VERSÃO ORIGINAL (preservada)
-- Salvo antes das correções em 2026-06-30. Ver análise/ajustes em relatorio_rca_metas.sql
-- Binds: :DTINI, :DTFIM (DD/MM/YYYY), :CODFILIAL, :CODUSUR, :SUPERVISOR
-- =============================================================================
SELECT
    BASE.DTINI
  , BASE.DTFIM
  , PCUSUARI.CODSUPERVISOR
  , BASE.CODUSUR AS RCA
  , PCUSUARI.NOME
  , BASE.VLMETA AS VALOR_META
  , BASE.VLDEVOL AS VALOR_DEVOLUCAO
  , BASE.VLVENDALIQ AS VALOR_LIQUIDA
  , NVL((CASE WHEN BASE.VLVENDALIQ > 0 AND BASE.VLMETA > 0 THEN ROUND(((BASE.VLVENDALIQ / BASE.VLMETA) * 100), 2) END), 0) PEC_META
  , ROUND(((NVL(BASE.VLMETA, 0) - NVL(BASE.VLVENDALIQ, 0)) / NVL(DIAS.DIASREST, 0)), 2) AS META_DIA
  , BASE.QTCLICART AS QT_CLIENTE_CARTEIRA
  , MIXMETA.meta_positivacao_cliente
  , BASE.QTCLIPOS AS POSITIVACAO_REALIZADO
  , NVL(BASE.MCLIPOS, 0) AS MEDIA_CLI_POSITIVADO
  , 'ABERTURA'
  , NVL(BASE.META_ABERTURA, 0) AS META_ABERTURA
  , BASE.QTCLIRESG AS QT_CLIENTE_REATIVADO
  , 'REATIVACAO'
  , BASE.META_REATIVACAO AS META_REATIVACAO
  , BASE.QTCLINOVO AS NOVOS_CLIENTES
  , 'MIX'
  , NVL(MIXMETA.MIXPREV, 0) AS META_MIX
  , MIX.QTMIXPRODUTO AS MIX_REALIZADO
  , CASE
        WHEN NVL((BASE.VLVENDALIQ / NULLIF(BASE.VLMETA, 0)) * 100, 0) >= 100
         AND NVL((BASE.QTCLIPOS / NULLIF(BASE.MCLIPOS, 0)) * 100, 0) >= 80 THEN 'OURO'
        WHEN NVL((BASE.VLVENDALIQ / NULLIF(BASE.VLMETA, 0)) * 100, 0) >= 80 THEN 'PRATA'
        ELSE 'BRONZE'
    END AS CLASSIFICACAO
FROM (
    SELECT
        TO_DATE(:DTINI, 'DD/MM/YYYY') AS DTINI
      , TO_DATE(:DTFIM, 'DD/MM/YYYY') AS DTFIM
      , NVL(SEQ.ROW_NUM, 0) SEQ
      , PCMETA.CODUSUR
      , PCMETA.VLMETA
      , NVL(FAT.QTPED, 0) QTPED
      , NVL(FAT.VLVENDBRUTA, 0) VLVENDBRUTA
      , NVL(FAT.VLDEVOL, 0) VLDEVOL
      , NVL(FAT.VLVENDALIQ, 0) VLVENDALIQ
      , CASE WHEN FAT.VLVENDALIQ > 0 AND PCMETA.VLMETA > 0 THEN NVL((TRUNC(((FAT.VLVENDALIQ / PCMETA.VLMETA) * 100), 2) - 100), 0) END CRESC
      , CASE WHEN FAT.VLVENDALIQ > 0 AND PCMETA.VLMETA > 0 THEN TRUNC(NVL(FAT.VLVENDALIQ, 0) - NVL(PCMETA.VLMETA, 0), 0) END DIF
      , NVL(CARTEIRA.QTCLICART, 0) QTCLICART
      , NVL(PCCLI.CLIATIVOS, 0) CLIATIVOS
      , ROUND((NVL(PCCLI.CLIATIVOS, FERIAS.QTCLITRANSFRCA) * 0.8), 2) MCLIPOS
      , NVL(CLIPOS.QTUSUR, 0) QTUSUR
      , NVL(CLIPOS.QTCLIPOS, 0) QTCLIPOS
      , NVL(NOVOS.QTCLINOVO, 0) QTCLINOVO
      , NVL(RESGATE.QTCLIRESG, 0) QTCLIRESG
      , NVL(METAA.META_ABERTURA, 0) AS META_ABERTURA
      , NVL(METAR.META_REATIVACAO, 0) AS META_REATIVACAO
    FROM (
        SELECT
            PCUSUARI.CODUSUR
          , SUM(NVL(PCMETARCA.VLVENDAPREV, 0)) VLMETA
        FROM PCMETARCA, PCUSUARI
        WHERE PCMETARCA.CODUSUR = PCUSUARI.CODUSUR
          AND PCMETARCA.DATA BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TO_DATE(:DTFIM, 'DD/MM/YYYY')
        GROUP BY PCUSUARI.CODUSUR
    ) PCMETA
    LEFT JOIN (
        SELECT CODUSUR, SUM(NVL(QTPEDPREV, 0)) AS META_ABERTURA
        FROM PCMETARCA
        WHERE DATA BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TO_DATE(:DTFIM, 'DD/MM/YYYY')
        GROUP BY CODUSUR
    ) METAA ON PCMETA.CODUSUR = METAA.CODUSUR
    LEFT JOIN (
        SELECT CODUSUR, SUM(NVL(QTITENSPEDPREV, 0)) AS META_REATIVACAO
        FROM PCMETARCA
        WHERE DATA BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TO_DATE(:DTFIM, 'DD/MM/YYYY')
        GROUP BY CODUSUR
    ) METAR ON PCMETA.CODUSUR = METAR.CODUSUR
    LEFT JOIN (
        SELECT VENDAS.CODUSUR, VENDAS.QTPED
          , ROUND(Nvl(VENDAS.VLVENDA, 0), 2) AS VLVENDBRUTA
          , ROUND(Nvl(DEVOL.VLVENDADEV, 0), 2) AS VLDEVOL
          , (ROUND(Nvl(VENDAS.VLVENDA, 0), 2) - ROUND(Nvl(DEVOL.VLVENDADEV, 0), 2)) AS VLVENDALIQ
        FROM (
            SELECT PCMOV.CODUSUR, COUNT(DISTINCT(PCMOV.NUMTRANSVENDA)) QTPED
              , SUM((NVL(PCMOV.VLVENDA, 0)) - (NVL(PCMOV.ICMSRETIDO, 0))) VLVENDA
              , SUM((NVL(PCMOV.VLTABELA, 0)) - (NVL(PCMOV.ICMSRETIDO, 0))) VLTABELA
            FROM VIEW_VENDAS_RESUMO_FATURAMENTO PCMOV
            WHERE 1 = 1 AND PCMOV.DTSAIDA BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TO_DATE(:DTFIM, 'DD/MM/YYYY')
              AND PCMOV.DTCANCEL IS NULL AND PCMOV.CODFILIAL IN (:CODFILIAL) AND PCMOV.CODOPER = 'S'
              AND PCMOV.CONDVENDA IN (1, 7, 9, 14) AND PCMOV.CODUSUR NOT IN (100, 400, 401, 402, 403)
            GROUP BY PCMOV.CODUSUR
        ) VENDAS
        FULL OUTER JOIN (
            SELECT PCMOVDEV.CODUSUR
              , SUM(NVL(PCMOVDEV.VLDEVOLUCAO, 0) - NVL(PCMOVDEV.VLST, 0)) AS VLVENDADEV
              , ROUND(SUM(NVL(PCMOVDEV.VLCUSTOFIN, 0) - NVL(PCMOVDEV.VLST, 0)), 2) AS VLCMVDEV
            FROM VIEW_DEVOL_RESUMO_FATURAMENTO PCMOVDEV
            WHERE PCMOVDEV.DTENT BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TO_DATE(:DTFIM, 'DD/MM/YYYY')
              AND PCMOVDEV.CODFILIAL IN (:CODFILIAL) AND PCMOVDEV.DTCANCEL IS NULL
              AND PCMOVDEV.CONDVENDA IN (1, 7, 9, 14) AND PCMOVDEV.CODUSUR NOT IN (100, 400, 401, 402, 403)
            GROUP BY PCMOVDEV.CODUSUR ORDER BY VLVENDADEV DESC
        ) DEVOL ON VENDAS.CODUSUR = DEVOL.CODUSUR
    ) FAT ON PCMETA.CODUSUR = FAT.CODUSUR
    LEFT JOIN (
        SELECT PCCLIENT.CODUSUR1 CODUSUR, COUNT(DISTINCT(PCCLIENT.CODCLI)) QTCLICART
        FROM PCCLIENT WHERE 1 = 1 GROUP BY PCCLIENT.CODUSUR1 ORDER BY PCCLIENT.CODUSUR1
    ) CARTEIRA ON PCMETA.CODUSUR = CARTEIRA.CODUSUR
    LEFT JOIN (
        SELECT PCCLIENT.CODUSUR1 CODUSUR, COUNT(DISTINCT(PCCLIENT.CODCLI)) CLIATIVOS
        FROM PCPEDC INNER JOIN PCCLIENT ON PCPEDC.CODCLI = PCCLIENT.CODCLI
        WHERE PCPEDC.CONDVENDA IN (1, 7, 9, 14) AND PCPEDC.DTCANCEL IS NULL
          AND PCPEDC.DATA BETWEEN ADD_MONTHS(TO_DATE(:DTINI, 'DD/MM/YYYY'), -3) AND ADD_MONTHS(TO_DATE(:DTFIM, 'DD/MM/YYYY'), -1)
          AND PCPEDC.CODFILIAL IN (:CODFILIAL)
        GROUP BY PCCLIENT.CODUSUR1 ORDER BY PCCLIENT.CODUSUR1
    ) PCCLI ON PCMETA.CODUSUR = PCCLI.CODUSUR
    LEFT JOIN (
        SELECT CODUSUR, COUNT(DISTINCT(CODUSUR)) QTUSUR, SUM(QTCLIPOS) QTCLIPOS
        FROM (
            SELECT PCPEDC.CODUSUR, COUNT(DISTINCT(PCPEDC.CODCLI)) QTCLIPOS
            FROM PCPEDC WHERE PCPEDC.CONDVENDA IN (1, 7, 9, 14) AND PCPEDC.DTCANCEL IS NULL
              AND PCPEDC.DATA BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TO_DATE(:DTFIM, 'DD/MM/YYYY')
              AND PCPEDC.CODFILIAL IN (:CODFILIAL)
            GROUP BY PCPEDC.CODUSUR
        ) POS GROUP BY CODUSUR
    ) CLIPOS ON PCMETA.CODUSUR = CLIPOS.CODUSUR
    LEFT JOIN (
        SELECT cl.codusur1 AS CODUSUR, COUNT(DISTINCT cl.codcli) AS QTCLINOVO
        FROM pcclient cl
        INNER JOIN pcmov pm ON pm.codcli = cl.codcli
        INNER JOIN pcpedc pp ON pp.numped = pm.numped AND pp.dtcancel IS NULL
           AND pp.condvenda IN (1, 7, 9, 14) AND pp.vltotal >= 120 --MAIOR OU IGUAL A 120 - 06/06/2026 - RIVELINO
        WHERE pm.codoper = 'S' AND pm.dtmov BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TO_DATE(:DTFIM, 'DD/MM/YYYY')
          AND NOT EXISTS (SELECT 1 FROM pcmov pm2 WHERE pm2.codcli = cl.codcli AND pm2.codoper = 'S' AND pm2.dtmov < TO_DATE(:DTINI, 'DD/MM/YYYY'))
        GROUP BY cl.codusur1
    ) NOVOS ON PCMETA.CODUSUR = NOVOS.CODUSUR
    LEFT JOIN (
        SELECT PCPEDC.CODUSUR, COUNT(DISTINCT PCPEDC.CODCLI) QTCLIRESG
        FROM PCPEDC WHERE PCPEDC.DATA BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TO_DATE(:DTFIM, 'DD/MM/YYYY')
          AND PCPEDC.DTCANCEL IS NULL AND PCPEDC.CONDVENDA IN (1, 7, 9) AND PCPEDC.POSICAO = 'F'
          AND PCPEDC.VLTOTAL >= 120 -- AJUSTES MAIOR OU IGUAL A 120
          AND NOT EXISTS (SELECT 1 FROM PCPEDC P WHERE P.CODCLI = PCPEDC.CODCLI AND P.DTCANCEL IS NULL
              AND P.CONDVENDA IN (1, 7, 9) AND P.POSICAO = 'F'
              AND P.DATA BETWEEN ADD_MONTHS(TO_DATE(:DTINI, 'DD/MM/YYYY'), -6) AND ADD_MONTHS(TO_DATE(:DTFIM, 'DD/MM/YYYY'), -1))
        GROUP BY PCPEDC.CODUSUR
    ) RESGATE ON PCMETA.CODUSUR = RESGATE.CODUSUR
    LEFT JOIN (
        SELECT VENDAS.CODUSUR
          , ROW_NUMBER() OVER (ORDER BY (ROUND(Nvl(VENDAS.VLVENDA, 0), 2) - ROUND(Nvl(DEVOL.VLVENDADEV, 0), 2)) DESC) AS ROW_NUM
        FROM (
            SELECT PCMOV.CODUSUR, SUM((NVL(PCMOV.VLVENDA, 0)) - (NVL(PCMOV.ICMSRETIDO, 0))) VLVENDA
              , SUM((NVL(PCMOV.VLTABELA, 0)) - (NVL(PCMOV.ICMSRETIDO, 0))) VLTABELA
            FROM VIEW_VENDAS_RESUMO_FATURAMENTO PCMOV
            WHERE 1 = 1 AND PCMOV.DTSAIDA BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TO_DATE(:DTFIM, 'DD/MM/YYYY')
              AND PCMOV.DTCANCEL IS NULL AND PCMOV.CODFILIAL IN (:CODFILIAL) AND PCMOV.CODOPER = 'S'
              AND PCMOV.CONDVENDA IN (1, 7, 9, 14) AND PCMOV.CODUSUR NOT IN (100, 400, 401, 402, 403)
            GROUP BY PCMOV.CODUSUR
        ) VENDAS
        FULL OUTER JOIN (
            SELECT PCMOVDEV.CODUSUR, SUM(NVL(PCMOVDEV.VLDEVOLUCAO, 0) - NVL(PCMOVDEV.VLST, 0)) AS VLVENDADEV
            FROM VIEW_DEVOL_RESUMO_FATURAMENTO PCMOVDEV
            WHERE PCMOVDEV.DTENT BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TO_DATE(:DTFIM, 'DD/MM/YYYY')
              AND PCMOVDEV.CODFILIAL IN (:CODFILIAL) AND PCMOVDEV.DTCancel IS NULL
              AND PCMOVDEV.CONDVENDA IN (1, 7, 9, 14) AND PCMOVDEV.CODUSUR NOT IN (100, 400, 401, 402, 403)
            GROUP BY PCMOVDEV.CODUSUR ORDER BY VLVENDADEV DESC
        ) DEVOL ON VENDAS.CODUSUR = DEVOL.CODUSUR
    ) SEQ ON PCMETA.CODUSUR = SEQ.CODUSUR
    LEFT JOIN (
        SELECT CODRCAORIGEM, COUNT(DISTINCT(NVL(TRANSFRCA.CODCLI, 0))) QTCLITRANSFRCA
        FROM (
            SELECT TRUNC(ADD_MONTHS(SYSDATE, -0), 'MM') DTINI, LAST_DAY(ADD_MONTHS(SYSDATE, -0)) DTFIM
              , PCMOVTRANSFRCA.CODRCAORIGEM, PCMOVTRANSFRCA.CODRCADESTINO, PCMOVTRANSFRCA.DTTRANSFERENCIA
              , PCMOVTRANSFRCA.CODCLI, PCMOVTRANSFRCA.OBSERVACAO
            FROM PCMOVTRANSFRCA, PCCLIENT, PCEMPR, PCUSUARI PCUSUARIORIGEM, PCUSUARI PCUSUARIDESTINO
            WHERE (PCMOVTRANSFRCA.CODCLI = PCCLIENT.CODCLI AND PCMOVTRANSFRCA.CODRCAORIGEM = PCUSUARIORIGEM.CODUSUR
              AND PCMOVTRANSFRCA.CODRCADESTINO = PCUSUARIDESTINO.CODUSUR AND PCMOVTRANSFRCA.OBSERVACAO LIKE '%FÉRIAS%'
              AND PCMOVTRANSFRCA.CODFUNC = PCEMPR.MATRICULA (+)
              AND PCMOVTRANSFRCA.DTTRANSFERENCIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE, -0), 'MM') AND LAST_DAY(ADD_MONTHS(SYSDATE, -0)))
        ) TRANSFRCA GROUP BY CODRCAORIGEM
    ) FERIAS ON PCMETA.CODUSUR = FERIAS.CODRCAORIGEM
) BASE
LEFT JOIN PCUSUARI ON BASE.CODUSUR = PCUSUARI.CODUSUR
LEFT JOIN (
    SELECT TO_DATE(:DTINI, 'DD/MM/YYYY') DTINI, DU.CODFILIAL, DU.DIASUTEIS, DI.DIASITEIS
      , CASE WHEN (DU.DIASUTEIS - DI.DIASITEIS) <= 0 THEN 1 ELSE (DU.DIASUTEIS - DI.DIASITEIS) + 1 END DIASREST
    FROM (
        SELECT CODFILIAL, COUNT(*) AS DIASUTEIS FROM PCDIASUTEIS
        WHERE DIAVENDAS = 'S' AND DATA BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TO_DATE(:DTFIM, 'DD/MM/YYYY') AND CODFILIAL IN ('20')
        GROUP BY CODFILIAL
    ) DU
    INNER JOIN (
        SELECT CODFILIAL, COUNT(*) AS DIASITEIS FROM PCDIASUTEIS
        WHERE DIAVENDAS = 'S' AND DATA BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TRUNC(SYSDATE) AND CODFILIAL IN ('20')
        GROUP BY CODFILIAL
    ) DI ON DU.CODFILIAL = DI.CODFILIAL
    GROUP BY DU.CODFILIAL, DU.DIASUTEIS, DI.DIASITEIS
) DIAS ON BASE.DTINI = DIAS.DTINI
LEFT JOIN (
    SELECT CODUSUR, SUM(QTMIXPRODUTO) AS QTMIXPRODUTO FROM (
        SELECT CODUSUR, QTMIXPRODUTO FROM TABLE(FUNC_RESUMOFATURAMENTO(P_CODFILIAL => '6', P_DATAINI => TO_DATE(:DTINI, 'DD/MM/YYYY'), P_DATAFIM => TO_DATE(:DTFIM, 'DD/MM/YYYY'), P_TIPOPESQUISA => '22', P_CONDVENDA => '1,7,9', P_TIPOVENDA10 => '0', P_BONIFICACAO => '1', P_DEVOLUCAO => '1', P_DESCST => '1', P_DESCIPI => '0', P_META => '0', P_LUCRO_LIQ => '0', P_CONSIDTIPOFJ => '0', P_CONSIDCONSUMIDORFINAL => '0', P_CONSIDISENTO => '0', P_CONSIDISENTA => '0', P_SUPERVMOV => '0', P_PRAZOADICIONAL => '0', P_CONSIDERARDEVOLTV8 => '0', P_DESCVLREPASSE => '0', P_DESCVLTABELA => '0', P_CONSIDERANOTASAPROVADAS => '0', P_DESCONSIDERARCLIVINCFORNEC => '0', P_CONSIDERACOBRANCATITULOS => '0', P_CONSIDERA_APLIC_VERBA => 'N', P_DESCFECP => '0'))
        UNION ALL
        SELECT CODUSUR, QTMIXPRODUTO FROM TABLE(FUNC_RESUMOFATURAMENTO(P_CODFILIAL => '20', P_DATAINI => TO_DATE(:DTINI, 'DD/MM/YYYY'), P_DATAFIM => TO_DATE(:DTFIM, 'DD/MM/YYYY'), P_TIPOPESQUISA => '22', P_CONDVENDA => '1,7,9', P_TIPOVENDA10 => '0', P_BONIFICACAO => '1', P_DEVOLUCAO => '1', P_DESCST => '1', P_DESCIPI => '0', P_META => '0', P_LUCRO_LIQ => '0', P_CONSIDTIPOFJ => '0', P_CONSIDCONSUMIDORFINAL => '0', P_CONSIDISENTO => '0', P_CONSIDISENTA => '0', P_SUPERVMOV => '0', P_PRAZOADICIONAL => '0', P_CONSIDERARDEVOLTV8 => '0', P_DESCVLREPASSE => '0', P_DESCVLTABELA => '0', P_CONSIDERANOTASAPROVADAS => '0', P_DESCONSIDERARCLIVINCFORNEC => '0', P_CONSIDERACOBRANCATITULOS => '0', P_CONSIDERA_APLIC_VERBA => 'N', P_DESCFECP => '0'))
        UNION ALL
        SELECT CODUSUR, QTMIXPRODUTO FROM TABLE(FUNC_RESUMOFATURAMENTO(P_CODFILIAL => '21', P_DATAINI => TO_DATE(:DTINI, 'DD/MM/YYYY'), P_DATAFIM => TO_DATE(:DTFIM, 'DD/MM/YYYY'), P_TIPOPESQUISA => '22', P_CONDVENDA => '1,7,9', P_TIPOVENDA10 => '0', P_BONIFICACAO => '1', P_DEVOLUCAO => '1', P_DESCST => '1', P_DESCIPI => '0', P_META => '0', P_LUCRO_LIQ => '0', P_CONSIDTIPOFJ => '0', P_CONSIDCONSUMIDORFINAL => '0', P_CONSIDISENTO => '0', P_CONSIDISENTA => '0', P_SUPERVMOV => '0', P_PRAZOADICIONAL => '0', P_CONSIDERARDEVOLTV8 => '0', P_DESCVLREPASSE => '0', P_DESCVLTABELA => '0', P_CONSIDERANOTASAPROVADAS => '0', P_DESCONSIDERARCLIVINCFORNEC => '0', P_CONSIDERACOBRANCATITULOS => '0', P_CONSIDERA_APLIC_VERBA => 'N', P_DESCFECP => '0'))
        UNION ALL
        SELECT CODUSUR, QTMIXPRODUTO FROM TABLE(FUNC_RESUMOFATURAMENTO(P_CODFILIAL => '22', P_DATAINI => TO_DATE(:DTINI, 'DD/MM/YYYY'), P_DATAFIM => TO_DATE(:DTFIM, 'DD/MM/YYYY'), P_TIPOPESQUISA => '22', P_CONDVENDA => '1,7,9', P_TIPOVENDA10 => '0', P_BONIFICACAO => '1', P_DEVOLUCAO => '1', P_DESCST => '1', P_DESCIPI => '0', P_META => '0', P_LUCRO_LIQ => '0', P_CONSIDTIPOFJ => '0', P_CONSIDCONSUMIDORFINAL => '0', P_CONSIDISENTO => '0', P_CONSIDISENTA => '0', P_SUPERVMOV => '0', P_PRAZOADICIONAL => '0', P_CONSIDERARDEVOLTV8 => '0', P_DESCVLREPASSE => '0', P_DESCVLTABELA => '0', P_CONSIDERANOTASAPROVADAS => '0', P_DESCONSIDERARCLIVINCFORNEC => '0', P_CONSIDERACOBRANCATITULOS => '0', P_CONSIDERA_APLIC_VERBA => 'N', P_DESCFECP => '0'))
        UNION ALL
        SELECT CODUSUR, QTMIXPRODUTO FROM TABLE(FUNC_RESUMOFATURAMENTO(P_CODFILIAL => '23', P_DATAINI => TO_DATE(:DTINI, 'DD/MM/YYYY'), P_DATAFIM => TO_DATE(:DTFIM, 'DD/MM/YYYY'), P_TIPOPESQUISA => '22', P_CONDVENDA => '1,7,9', P_TIPOVENDA10 => '0', P_BONIFICACAO => '1', P_DEVOLUCAO => '1', P_DESCST => '1', P_DESCIPI => '0', P_META => '0', P_LUCRO_LIQ => '0', P_CONSIDTIPOFJ => '0', P_CONSIDCONSUMIDORFINAL => '0', P_CONSIDISENTO => '0', P_CONSIDISENTA => '0', P_SUPERVMOV => '0', P_PRAZOADICIONAL => '0', P_CONSIDERARDEVOLTV8 => '0', P_DESCVLREPASSE => '0', P_DESCVLTABELA => '0', P_CONSIDERANOTASAPROVADAS => '0', P_DESCONSIDERARCLIVINCFORNEC => '0', P_CONSIDERACOBRANCATITULOS => '0', P_CONSIDERA_APLIC_VERBA => 'N', P_DESCFECP => '0'))
    ) GROUP BY CODUSUR
) MIX ON BASE.CODUSUR = MIX.CODUSUR
LEFT JOIN (
    SELECT CODUSUR, MAX(MIXPREV) KEEP (DENSE_RANK LAST ORDER BY DATA) AS MIXPREV
      , MAX(cliposprev) KEEP (DENSE_RANK LAST ORDER BY data) AS meta_positivacao_cliente
    FROM PCMETA WHERE DATA BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TO_DATE(:DTFIM, 'DD/MM/YYYY') AND TIPOMETA = 'M'
    GROUP BY CODUSUR
) MIXMETA ON BASE.CODUSUR = MIXMETA.CODUSUR
WHERE PCUSUARI.BLOQUEIO = 'N'
  AND PCUSUARI.CODUSUR IN (:CODUSUR)
  AND PCUSUARI.CODSUPERVISOR IN (:SUPERVISOR)
ORDER BY BASE.VLVENDALIQ DESC
