-- =============================================================================
-- Relatório de METAS por RCA (vendedor) — VERSÃO CORRIGIDA (2026-06-30)
-- Original preservado em relatorio_rca_metas_ORIGINAL.sql
-- Ajustes:
--  1. META_DIA: evita ÷0 (NULLIF/NVL(...,1) no DIASREST).
--  2. Removido o join SEQ (ROW_NUMBER) que era calculado e nunca usado.
--  3. FAT/DEVOL: COALESCE(VENDAS.CODUSUR, DEVOL.CODUSUR) p/ não perder devolução-sem-venda.
--  4. Escopo de filial unificado: MIX, DIAS, NOVOS e RESGATE agora respeitam :CODFILIAL.
--  5. CONDVENDA padronizada em (1,7,9,14) em todas as métricas (inclui MIX e RESGATE).
--  6. FERIAS usa o período :DTINI/:DTFIM (antes era mês corrente fixo).
--  7. Binds opcionais para :CODUSUR e :SUPERVISOR (IS NULL = todos).
-- Binds: :DTINI, :DTFIM (DD/MM/YYYY), :CODFILIAL (uma filial), :CODUSUR, :SUPERVISOR
-- =============================================================================
SELECT
    BASE.DTINI
  , BASE.DTFIM
  , PCUSUARI.CODSUPERVISOR
  , BASE.CODUSUR AS RCA
  , PCUSUARI.NOME
  , BASE.VLMETA AS VALOR_META
  , BASE.VLDEVOL AS VALOR_DEVOLUCAO
  , BASE.VLVENDALIQ AS VALOR_LIQUIDA
  , NVL((CASE WHEN BASE.VLVENDALIQ > 0 AND BASE.VLMETA > 0 THEN ROUND(((BASE.VLVENDALIQ / BASE.VLMETA) * 100), 2) END), 0) PEC_META
  , ROUND((NVL(BASE.VLMETA, 0) - NVL(BASE.VLVENDALIQ, 0)) / NULLIF(NVL(DIAS.DIASREST, 1), 0), 2) AS META_DIA
  , BASE.QTCLICART AS QT_CLIENTE_CARTEIRA
  , NVL(MIXMETA.meta_positivacao_cliente, 0) AS META_POSITIVACAO
  , BASE.QTCLIPOS AS POSITIVACAO_REALIZADO
  , NVL(BASE.MCLIPOS, 0) AS MEDIA_CLI_POSITIVADO
  , NVL(BASE.META_ABERTURA, 0) AS META_ABERTURA
  , BASE.QTCLINOVO AS NOVOS_CLIENTES
  , NVL(BASE.META_REATIVACAO, 0) AS META_REATIVACAO
  , BASE.QTCLIRESG AS QT_CLIENTE_REATIVADO
  , NVL(MIXMETA.MIXPREV, 0) AS META_MIX
  , NVL(MIX.QTMIXPRODUTO, 0) AS MIX_REALIZADO
  , CASE
        WHEN NVL((BASE.VLVENDALIQ / NULLIF(BASE.VLMETA, 0)) * 100, 0) >= 100
         AND NVL((BASE.QTCLIPOS / NULLIF(BASE.MCLIPOS, 0)) * 100, 0) >= 80 THEN 'OURO'
        WHEN NVL((BASE.VLVENDALIQ / NULLIF(BASE.VLMETA, 0)) * 100, 0) >= 80 THEN 'PRATA'
        ELSE 'BRONZE'
    END AS CLASSIFICACAO
FROM (
    SELECT
        TO_DATE(:DTINI, 'DD/MM/YYYY') AS DTINI
      , TO_DATE(:DTFIM, 'DD/MM/YYYY') AS DTFIM
      , PCMETA.CODUSUR
      , PCMETA.VLMETA
      , NVL(FAT.VLDEVOL, 0) VLDEVOL
      , NVL(FAT.VLVENDALIQ, 0) VLVENDALIQ
      , NVL(CARTEIRA.QTCLICART, 0) QTCLICART
      , NVL(PCCLI.CLIATIVOS, 0) CLIATIVOS
      , ROUND((NVL(PCCLI.CLIATIVOS, FERIAS.QTCLITRANSFRCA) * 0.8), 2) MCLIPOS
      , NVL(CLIPOS.QTCLIPOS, 0) QTCLIPOS
      , NVL(NOVOS.QTCLINOVO, 0) QTCLINOVO
      , NVL(RESGATE.QTCLIRESG, 0) QTCLIRESG
      , NVL(METAA.META_ABERTURA, 0) AS META_ABERTURA
      , NVL(METAR.META_REATIVACAO, 0) AS META_REATIVACAO
    FROM (
        SELECT PCUSUARI.CODUSUR, SUM(NVL(PCMETARCA.VLVENDAPREV, 0)) VLMETA
        FROM PCMETARCA, PCUSUARI
        WHERE PCMETARCA.CODUSUR = PCUSUARI.CODUSUR
          AND PCMETARCA.DATA BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TO_DATE(:DTFIM, 'DD/MM/YYYY')
        GROUP BY PCUSUARI.CODUSUR
    ) PCMETA
    LEFT JOIN (
        SELECT CODUSUR, SUM(NVL(QTPEDPREV, 0)) AS META_ABERTURA
        FROM PCMETARCA
        WHERE DATA BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TO_DATE(:DTFIM, 'DD/MM/YYYY')
        GROUP BY CODUSUR
    ) METAA ON PCMETA.CODUSUR = METAA.CODUSUR
    LEFT JOIN (
        SELECT CODUSUR, SUM(NVL(QTITENSPEDPREV, 0)) AS META_REATIVACAO
        FROM PCMETARCA
        WHERE DATA BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TO_DATE(:DTFIM, 'DD/MM/YYYY')
        GROUP BY CODUSUR
    ) METAR ON PCMETA.CODUSUR = METAR.CODUSUR
    LEFT JOIN (
        -- (3) COALESCE para não perder RCA com devolução e sem venda no período
        SELECT COALESCE(VENDAS.CODUSUR, DEVOL.CODUSUR) AS CODUSUR
          , ROUND(NVL(VENDAS.VLVENDA, 0), 2) AS VLVENDBRUTA
          , ROUND(NVL(DEVOL.VLVENDADEV, 0), 2) AS VLDEVOL
          , (ROUND(NVL(VENDAS.VLVENDA, 0), 2) - ROUND(NVL(DEVOL.VLVENDADEV, 0), 2)) AS VLVENDALIQ
        FROM (
            SELECT PCMOV.CODUSUR, SUM(NVL(PCMOV.VLVENDA, 0) - NVL(PCMOV.ICMSRETIDO, 0)) VLVENDA
            FROM VIEW_VENDAS_RESUMO_FATURAMENTO PCMOV
            WHERE PCMOV.DTSAIDA BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TO_DATE(:DTFIM, 'DD/MM/YYYY')
              AND PCMOV.DTCANCEL IS NULL AND PCMOV.CODFILIAL IN (:CODFILIAL) AND PCMOV.CODOPER = 'S'
              AND PCMOV.CONDVENDA IN (1, 7, 9, 14) AND PCMOV.CODUSUR NOT IN (100, 400, 401, 402, 403)
            GROUP BY PCMOV.CODUSUR
        ) VENDAS
        FULL OUTER JOIN (
            SELECT PCMOVDEV.CODUSUR, SUM(NVL(PCMOVDEV.VLDEVOLUCAO, 0) - NVL(PCMOVDEV.VLST, 0)) AS VLVENDADEV
            FROM VIEW_DEVOL_RESUMO_FATURAMENTO PCMOVDEV
            WHERE PCMOVDEV.DTENT BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TO_DATE(:DTFIM, 'DD/MM/YYYY')
              AND PCMOVDEV.CODFILIAL IN (:CODFILIAL) AND PCMOVDEV.DTCANCEL IS NULL
              AND PCMOVDEV.CONDVENDA IN (1, 7, 9, 14) AND PCMOVDEV.CODUSUR NOT IN (100, 400, 401, 402, 403)
            GROUP BY PCMOVDEV.CODUSUR
        ) DEVOL ON VENDAS.CODUSUR = DEVOL.CODUSUR
    ) FAT ON PCMETA.CODUSUR = FAT.CODUSUR
    LEFT JOIN (
        SELECT PCCLIENT.CODUSUR1 CODUSUR, COUNT(DISTINCT(PCCLIENT.CODCLI)) QTCLICART
        FROM PCCLIENT GROUP BY PCCLIENT.CODUSUR1
    ) CARTEIRA ON PCMETA.CODUSUR = CARTEIRA.CODUSUR
    LEFT JOIN (
        SELECT PCCLIENT.CODUSUR1 CODUSUR, COUNT(DISTINCT(PCCLIENT.CODCLI)) CLIATIVOS
        FROM PCPEDC INNER JOIN PCCLIENT ON PCPEDC.CODCLI = PCCLIENT.CODCLI
        WHERE PCPEDC.CONDVENDA IN (1, 7, 9, 14) AND PCPEDC.DTCANCEL IS NULL
          AND PCPEDC.DATA BETWEEN ADD_MONTHS(TO_DATE(:DTINI, 'DD/MM/YYYY'), -3) AND ADD_MONTHS(TO_DATE(:DTFIM, 'DD/MM/YYYY'), -1)
          AND PCPEDC.CODFILIAL IN (:CODFILIAL)
        GROUP BY PCCLIENT.CODUSUR1
    ) PCCLI ON PCMETA.CODUSUR = PCCLI.CODUSUR
    LEFT JOIN (
        SELECT PCPEDC.CODUSUR, COUNT(DISTINCT(PCPEDC.CODCLI)) QTCLIPOS
        FROM PCPEDC WHERE PCPEDC.CONDVENDA IN (1, 7, 9, 14) AND PCPEDC.DTCANCEL IS NULL
          AND PCPEDC.DATA BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TO_DATE(:DTFIM, 'DD/MM/YYYY')
          AND PCPEDC.CODFILIAL IN (:CODFILIAL)
        GROUP BY PCPEDC.CODUSUR
    ) CLIPOS ON PCMETA.CODUSUR = CLIPOS.CODUSUR
    LEFT JOIN (
        -- (4) Novos clientes agora respeitam :CODFILIAL no período; "nunca comprou antes" segue global
        SELECT cl.codusur1 AS CODUSUR, COUNT(DISTINCT cl.codcli) AS QTCLINOVO
        FROM pcclient cl
        INNER JOIN pcmov pm ON pm.codcli = cl.codcli
        INNER JOIN pcpedc pp ON pp.numped = pm.numped AND pp.dtcancel IS NULL
           AND pp.condvenda IN (1, 7, 9, 14) AND pp.vltotal >= 120
        WHERE pm.codoper = 'S' AND pm.codfilial IN (:CODFILIAL)
          AND pm.dtmov BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TO_DATE(:DTFIM, 'DD/MM/YYYY')
          AND NOT EXISTS (SELECT 1 FROM pcmov pm2 WHERE pm2.codcli = cl.codcli AND pm2.codoper = 'S' AND pm2.dtmov < TO_DATE(:DTINI, 'DD/MM/YYYY'))
        GROUP BY cl.codusur1
    ) NOVOS ON PCMETA.CODUSUR = NOVOS.CODUSUR
    LEFT JOIN (
        -- (4)(5) Reativação por :CODFILIAL e CONDVENDA padronizada (1,7,9,14)
        -- (8) Exclui CLIENTES NOVOS: reativado tem de ter histórico ANTES da janela de
        --     inatividade. Sem isso, um cliente novo (1ª compra no período) entrava como
        --     reativado também (não tinha compra nos 6 meses anteriores). Confirmado: cliente
        --     55880 da RCA 93 era contado em NOVOS e em RESGATE ao mesmo tempo.
        SELECT PCPEDC.CODUSUR, COUNT(DISTINCT PCPEDC.CODCLI) QTCLIRESG
        FROM PCPEDC WHERE PCPEDC.DATA BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TO_DATE(:DTFIM, 'DD/MM/YYYY')
          AND PCPEDC.DTCANCEL IS NULL AND PCPEDC.CONDVENDA IN (1, 7, 9, 14) AND PCPEDC.POSICAO = 'F'
          AND PCPEDC.VLTOTAL >= 120 AND PCPEDC.CODFILIAL IN (:CODFILIAL)
          AND NOT EXISTS (SELECT 1 FROM PCPEDC P WHERE P.CODCLI = PCPEDC.CODCLI AND P.DTCANCEL IS NULL
              AND P.CONDVENDA IN (1, 7, 9, 14) AND P.POSICAO = 'F'
              AND P.DATA BETWEEN ADD_MONTHS(TO_DATE(:DTINI, 'DD/MM/YYYY'), -6) AND ADD_MONTHS(TO_DATE(:DTFIM, 'DD/MM/YYYY'), -1))
          AND EXISTS (SELECT 1 FROM PCPEDC P3 WHERE P3.CODCLI = PCPEDC.CODCLI AND P3.DTCANCEL IS NULL
              AND P3.CONDVENDA IN (1, 7, 9, 14) AND P3.POSICAO = 'F'
              AND P3.DATA < ADD_MONTHS(TO_DATE(:DTINI, 'DD/MM/YYYY'), -6))
        GROUP BY PCPEDC.CODUSUR
    ) RESGATE ON PCMETA.CODUSUR = RESGATE.CODUSUR
    LEFT JOIN (
        -- (6) FERIAS no período do relatório (antes era mês corrente fixo)
        SELECT T.CODRCAORIGEM, COUNT(DISTINCT(NVL(T.CODCLI, 0))) QTCLITRANSFRCA
        FROM PCMOVTRANSFRCA T, PCCLIENT, PCUSUARI PCUSUARIORIGEM, PCUSUARI PCUSUARIDESTINO
        WHERE T.CODCLI = PCCLIENT.CODCLI AND T.CODRCAORIGEM = PCUSUARIORIGEM.CODUSUR
          AND T.CODRCADESTINO = PCUSUARIDESTINO.CODUSUR AND T.OBSERVACAO LIKE '%FÉRIAS%'
          AND T.DTTRANSFERENCIA BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TO_DATE(:DTFIM, 'DD/MM/YYYY')
        GROUP BY T.CODRCAORIGEM
    ) FERIAS ON PCMETA.CODUSUR = FERIAS.CODRCAORIGEM
) BASE
LEFT JOIN PCUSUARI ON BASE.CODUSUR = PCUSUARI.CODUSUR
LEFT JOIN (
    -- (1)(4) Dias restantes pela filial do relatório (:CODFILIAL)
    SELECT TO_DATE(:DTINI, 'DD/MM/YYYY') DTINI
      , CASE WHEN (DU.DIASUTEIS - DI.DIASUTEISDEC) <= 0 THEN 1 ELSE (DU.DIASUTEIS - DI.DIASUTEISDEC) + 1 END DIASREST
    FROM (
        SELECT COUNT(*) AS DIASUTEIS FROM PCDIASUTEIS
        WHERE DIAVENDAS = 'S' AND DATA BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TO_DATE(:DTFIM, 'DD/MM/YYYY') AND CODFILIAL IN (:CODFILIAL)
    ) DU
    CROSS JOIN (
        SELECT COUNT(*) AS DIASUTEISDEC FROM PCDIASUTEIS
        WHERE DIAVENDAS = 'S' AND DATA BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TRUNC(SYSDATE) AND CODFILIAL IN (:CODFILIAL)
    ) DI
) DIAS ON BASE.DTINI = DIAS.DTINI
LEFT JOIN (
    -- (4)(5) MIX por :CODFILIAL e CONDVENDA padronizada (1,7,9,14)
    SELECT CODUSUR, SUM(QTMIXPRODUTO) AS QTMIXPRODUTO
    FROM TABLE(FUNC_RESUMOFATURAMENTO(P_CODFILIAL => :CODFILIAL, P_DATAINI => TO_DATE(:DTINI, 'DD/MM/YYYY'), P_DATAFIM => TO_DATE(:DTFIM, 'DD/MM/YYYY'), P_TIPOPESQUISA => '22', P_CONDVENDA => '1,7,9,14', P_TIPOVENDA10 => '0', P_BONIFICACAO => '1', P_DEVOLUCAO => '1', P_DESCST => '1', P_DESCIPI => '0', P_META => '0', P_LUCRO_LIQ => '0', P_CONSIDTIPOFJ => '0', P_CONSIDCONSUMIDORFINAL => '0', P_CONSIDISENTO => '0', P_CONSIDISENTA => '0', P_SUPERVMOV => '0', P_PRAZOADICIONAL => '0', P_CONSIDERARDEVOLTV8 => '0', P_DESCVLREPASSE => '0', P_DESCVLTABELA => '0', P_CONSIDERANOTASAPROVADAS => '0', P_DESCONSIDERARCLIVINCFORNEC => '0', P_CONSIDERACOBRANCATITULOS => '0', P_CONSIDERA_APLIC_VERBA => 'N', P_DESCFECP => '0'))
    GROUP BY CODUSUR
) MIX ON BASE.CODUSUR = MIX.CODUSUR
LEFT JOIN (
    SELECT CODUSUR, MAX(MIXPREV) KEEP (DENSE_RANK LAST ORDER BY DATA) AS MIXPREV
      , MAX(CLIPOSPREV) KEEP (DENSE_RANK LAST ORDER BY DATA) AS META_POSITIVACAO_CLIENTE
    FROM PCMETA WHERE DATA BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TO_DATE(:DTFIM, 'DD/MM/YYYY') AND TIPOMETA = 'M'
    GROUP BY CODUSUR
) MIXMETA ON BASE.CODUSUR = MIXMETA.CODUSUR
WHERE PCUSUARI.BLOQUEIO = 'N'
  AND (:CODUSUR IS NULL OR PCUSUARI.CODUSUR = :CODUSUR)
  AND (:SUPERVISOR IS NULL OR PCUSUARI.CODSUPERVISOR = :SUPERVISOR)
ORDER BY BASE.VLVENDALIQ DESC
